### ISSUE TITLE
is possible to configure the Buspirate V4 as JTAG programmer?

### ISSUE THREAD

**Issue by darkomen** [BusPirate/Bus_Pirate#44] opened 2017-01-31 08:42 UTC
Hello, I need a JTAG programmer, and I want to know if I could use the buspirate in this case or I have to get a programmer

**Comment by agatti** [comment] 2017-02-02 17:46
Hi there, this is planned for version 7.2.  Please follow bug #28 for further developments.

Closing as duplicate of #28.

**Closed by agatti** 2017-02-02 17:46 UTC
